name: mygeoflow
description: "GeoFlow Mobile - Leak Monitoring App"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.0.7
  camera: ^0.11.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  # - assets/lightmodelogo.png